[pytest]
addopts = -vs --alluredir  testcase/report/temp  -p no:warnings
;--clean-alluredir
;
testpaths =  ./testcase/

filterwarnings =
    error
    ignore::UserWarning

python_files = test_*.py

python_classes = Test*

python_functions = test

markers =
    login: '登录模块'
    logfail: '登录失败用例'



